# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  # name = "Posts"
  name = "Writings"
  pageRef = "/posts"
  title = "Writings"
  weight = 10

# [[main]]
#   name = "Archives"
#   pageRef = "/archives"
#   weight = 20

[[main]]
  name = "About"
  pageRef = "/about"
  title = "About"
  weight = 30

[[main]]
  name = "Projects"
  pageRef = "/projects"
  title = "Projects"
  weight = 40

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

[[main]]
  pre = "github"
  title = "Github"
  url = "https://github.com/mksalada"
  weight = 50

# [[main]]
#   pre = "hashnode"
#   title = "Hashnode"
#   url = "https://hashnode.com/@tinasalada"
#   weight = 60

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   pre = "hashnode"
#   title = "Hashnode"
#   url = "https://hashnode.com/@tinasalada"
#   weight = 10

[[footer]]
  # pre = "tags"
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[footer]]
  # pre = "heart"
  name = "Credits"
  pageRef = "credits"
  weight = 30

[[footer]]
  pre = "creative-commons"
  title = "CC BY-NC-ND 4.0"
  fill = "currentColor"
  url = "http://creativecommons.org/licenses/by-nc-nd/4.0/"
  weight = 40
